version: '3.8'

services:
  backend:
    build:
      context: ./technical-test-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./technical-test-back:/app
    environment:
      - NODE_ENV=production
   

  frontend:
    build:
      context: ./test-envoiture
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend